window.TENDER_DATA = {
  "updatedAt": "2026-06-05T17:31:33.205Z",
  "profile": {
    "title": "Bau-Ausschreibungen Dashboard",
    "owner": "Adriano",
    "scope": [
      "Bundesweit",
      "Hochbau",
      "Tiefbau",
      "Brueckenbau und Ingenieurbauwerke",
      "Oeffentliche Ausschreibungen",
      "Private und gewerbliche Bauvorhaben"
    ],
    "sources": [
      {
        "name": "service.bund.de",
        "url": "https://www.service.bund.de/Content/DE/Ausschreibungen/Suche/Formular.html"
      },
      {
        "name": "eVergabe Hochbau",
        "url": "https://www.evergabe.de/ausschreibungen-hochbau"
      },
      {
        "name": "eVergabe Tiefbau",
        "url": "https://www.evergabe.de/ausschreibungen-tiefbau"
      },
      {
        "name": "eVergabe Brueckenbau",
        "url": "https://www.evergabe.de/ausschreibungen-brueckenbau-tunnelbau"
      },
      {
        "name": "DEGES",
        "url": "https://vergabe.deges.de/NetServer/index.jsp?function=Search"
      },
      {
        "name": "aumass",
        "url": "https://www.aumass.de/ausschreibungen"
      },
      {
        "name": "ibau",
        "url": "https://www.ibau.de/"
      },
      {
        "name": "greenprofi",
        "url": "https://www.greenprofi.de/"
      }
    ]
  },
  "tenders": [
    {
      "id": "gewerk-002-erdarbeiten-entwasserung-stadt-bad-bramstedt-veroeffentlichungsende-0",
      "title": "Gewerk 002 - Erdarbeiten / Entwässerung",
      "client": "Stadt Bad Bramstedt",
      "location": "24576 Bad Bramstedt",
      "state": "Bundesweit",
      "deadline": "2026-06-05T23:59:00+02:00",
      "execution": "Noch pruefen",
      "category": "Tiefbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Dringend",
      "summary": "Erfuellungsort: 24576 Bad Bramstedt Vergabestelle: Stadt Bad Bramstedt Angebotsfrist: Veroeffentlichungsende: 05.06.2026 23:59",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/dtvp/2026/06/328807.html"
    },
    {
      "id": "ministerium-fur-wirtschaft-tourismus-landwirtschaft-und-forsten-des-landes-sachs",
      "title": "Ministerium für Wirtschaft, Tourismus, Landwirtschaft und Forsten des Landes Sachsen-Anhalt / Modernisierung der Überbetrieblichen Ausbildungsstätte in Iden – Erdbauarbeiten Erschließung",
      "client": "Ministerium für Wirtschaft, Tourismus, Landwirtschaft und Forsten des Landes Sachsen-Anhalt",
      "location": "39606 Iden (Altmark)",
      "state": "Bundesweit",
      "deadline": "2026-06-10T12:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Dringend",
      "summary": "Erfuellungsort: 39606 Iden (Altmark) Vergabestelle: Ministerium für Wirtschaft, Tourismus, Landwirtschaft und Forsten des Landes Sachsen-Anhalt Angebotsfrist: 10.06.2026 12:00 Veroeffentlichungsende: 10.06.2026 12:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/evergabede/2026/06/6949880.html"
    },
    {
      "id": "energetische-sanierung-haus-1-los-3-gerustbau-landkreis-mansfeld-sudharz-11-06-2",
      "title": "Energetische Sanierung Haus 1 - Los 3 Gerüstbau",
      "client": "Landkreis Mansfeld-Südharz",
      "location": "06526 Sangerhausen",
      "state": "Bundesweit",
      "deadline": "2026-06-11T09:30:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Dringend",
      "summary": "Erfuellungsort: 06526 Sangerhausen Vergabestelle: Landkreis Mansfeld-Südharz Angebotsfrist: 11.06.2026 09:30 Veroeffentlichungsende: 11.06.2026 09:30",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/evergabede/2026/06/6950323.html"
    },
    {
      "id": "s-06-grundschule-wittelsbach-pirmasens-maler-burkel-strasse-24-66954-pirmasens-m",
      "title": "S 06 Grundschule Wittelsbach Pirmasens, Maler-Bürkel-Straße 24, 66954 Pirmasens - Malerarbeiten",
      "client": "Stadtverwaltung Pirmasens - 69 Gebäudemanagement",
      "location": "66954 Pirmasens",
      "state": "Bundesweit",
      "deadline": "2026-06-14T10:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Tiefbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 66954 Pirmasens Vergabestelle: Stadtverwaltung Pirmasens - 69 Gebäudemanagement Angebotsfrist: Veroeffentlichungsende: 14.06.2026 10:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/editor/Stadtverwaltung-Pirmasens/2026/06/6528378.html"
    },
    {
      "id": "stadt-cottbus-ex-ante-129-2026-opnv-haltestellen-kiekebuscher-strasse-tierpark-s",
      "title": "Stadt Cottbus - Ex-ante 129-2026 ÖPNV-Haltestellen Kiekebuscher Straße/Tierpark - stadteinwärts und stadtauswärts",
      "client": "Stadtverwaltung Cottbus Fachbereich Grün- und Verkehrsflächen",
      "location": "03042 Cottbus",
      "state": "Bundesweit",
      "deadline": "2026-06-15T00:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Tiefbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 03042 Cottbus Vergabestelle: Stadtverwaltung Cottbus Fachbereich Grün- und Verkehrsflächen Angebotsfrist: Veroeffentlichungsende: 15.06.2026 00:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/vmp-bb/2026/06/254537.html"
    },
    {
      "id": "tud-gerber-bau-brandschutzmassnahmen-staatsbetrieb-sachsisches-immobilien-und-ba",
      "title": "TUD, Gerber-Bau Brandschutzmaßnahmen",
      "client": "Staatsbetrieb Sächsisches Immobilien- und Baumanagement, Zentrale, Zentralstelle Vergabe- und Vertragsmanagement",
      "location": "TUD, Gerber-Bau Brandschutzmaßnahmen Zellescher Weg, 01217 Dresden",
      "state": "Bundesweit",
      "deadline": "2026-06-15T09:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: TUD, Gerber-Bau Brandschutzmaßnahmen Zellescher Weg, 01217 Dresden Vergabestelle: Staatsbetrieb Sächsisches Immobilien- und Baumanagement, Zentrale, Zentralstelle Vergabe- und Vertragsmanagement Angebotsfrist: 15.06.2026 09:00 Veroeffentlichungsende: 15.06.2026 23:59",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/sib/2026/06/54321-Tender-19d852c3722-510b90be9a93c6df.html"
    },
    {
      "id": "sanierung-grundschule-drossdorf-los-2-metallbauarbeiten-fluchttreppe-klasse-1-04",
      "title": "Sanierung Grundschule Droßdorf - Los 2 Metallbauarbeiten Fluchttreppe Klasse 1.04",
      "client": "Verbandsgemeinde Droyßiger-Zeitzer Forst",
      "location": "06712 Gutenborn OT Droßdorf",
      "state": "Bundesweit",
      "deadline": "2026-06-15T10:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 06712 Gutenborn OT Droßdorf Vergabestelle: Verbandsgemeinde Droyßiger-Zeitzer Forst Angebotsfrist: 15.06.2026 10:00 Veroeffentlichungsende: 15.06.2026 10:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/evergabede/2026/06/6948947.html"
    },
    {
      "id": "sanierung-grundschule-drossdorf-los-3-metallbauarbeiten-fluchttur-klasse-1-04-ve",
      "title": "Sanierung Grundschule Droßdorf - Los 3-Metallbauarbeiten Fluchttür Klasse 1.04",
      "client": "Verbandsgemeinde Droyßiger-Zeitzer Forst",
      "location": "06712 Gutenborn OT Droßdorf",
      "state": "Bundesweit",
      "deadline": "2026-06-15T11:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 06712 Gutenborn OT Droßdorf Vergabestelle: Verbandsgemeinde Droyßiger-Zeitzer Forst Angebotsfrist: 15.06.2026 11:00 Veroeffentlichungsende: 15.06.2026 11:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/evergabede/2026/06/6948945.html"
    },
    {
      "id": "sanierung-grundschule-drossdorf-los-4-aufzugsanlage-verbandsgemeinde-droyssiger-",
      "title": "Sanierung Grundschule Droßdorf - Los 4 -Aufzugsanlage",
      "client": "Verbandsgemeinde Droyßiger-Zeitzer Forst",
      "location": "06712 Gutenborn OT Droßdorf",
      "state": "Bundesweit",
      "deadline": "2026-06-15T12:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 06712 Gutenborn OT Droßdorf Vergabestelle: Verbandsgemeinde Droyßiger-Zeitzer Forst Angebotsfrist: 15.06.2026 12:00 Veroeffentlichungsende: 15.06.2026 12:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/evergabede/2026/06/6950133.html"
    },
    {
      "id": "druck-von-faltblattern-mit-einer-auflage-von-50-000-stuck-landesamt-fur-schule-u",
      "title": "Druck von Faltblättern mit einer Auflage von 50.000 Stück",
      "client": "Landesamt für Schule und Bildung",
      "location": "Deutschland",
      "state": "Bundesweit",
      "deadline": "2026-06-15T23:59:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: Deutschland Vergabestelle: Landesamt für Schule und Bildung Angebotsfrist: 15.06.2026 23:59 Veroeffentlichungsende: 15.06.2026 23:59",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/ai-sachsen/2026/06/54321-Tender-19e88ac819d-5ee604b9652bb772.html"
    },
    {
      "id": "d-tud-munchner-schumann-helmholtz-nothnitz-blend-und-sonnenschutz-staatsbetrieb-",
      "title": "D-TUD Münchner-Schumann-Helmholtz-Nöthnitz, Blend- und Sonnenschutz",
      "client": "Staatsbetrieb Sächsisches Immobilien- und Baumanagement, Zentrale, Zentralstelle Vergabe- und Vertragsmanagement",
      "location": "Dresden",
      "state": "Bundesweit",
      "deadline": "2026-06-15T23:59:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: Dresden Vergabestelle: Staatsbetrieb Sächsisches Immobilien- und Baumanagement, Zentrale, Zentralstelle Vergabe- und Vertragsmanagement Angebotsfrist: Veroeffentlichungsende: 15.06.2026 23:59",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/sib/2026/06/54321-PublishingProcess-19e8e07f4d5-1fbfe3734cc7dcd3.html"
    },
    {
      "id": "sanierung-erneuerung-der-fussgangeruberfuhrung-am-bahnhof-in-04600-altenburg-sta",
      "title": "Sanierung / Erneuerung der Fußgängerüberführung am Bahnhof in 04600 Altenburg",
      "client": "Stadt Altenburg - Stadtverwaltung Altenburg",
      "location": "04600 Altenburg",
      "state": "Bundesweit",
      "deadline": "2026-06-16T08:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Bruecken",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 04600 Altenburg Vergabestelle: Stadt Altenburg - Stadtverwaltung Altenburg Angebotsfrist: 16.06.2026 08:00 Veroeffentlichungsende: 17.07.2026 00:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/subreport/2026/05/E69261236.html"
    },
    {
      "id": "lieferung-von-access-points-und-switches-fur-die-alice-salomon-schule-bbs-der-re",
      "title": "Lieferung von Access Points und Switches für die Alice-Salomon-Schule BBS der Region Hannover",
      "client": "Region Hannover",
      "location": "30419 Hannover",
      "state": "Bundesweit",
      "deadline": "2026-06-16T08:45:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 30419 Hannover Vergabestelle: Region Hannover Angebotsfrist: 16.06.2026 08:45 Veroeffentlichungsende: 16.06.2026 08:45",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/evergabede/2026/06/6950219.html"
    },
    {
      "id": "sicherheitsdienstleistungen-internat-der-mullerschule-wittingen-landkreis-gifhor",
      "title": "Sicherheitsdienstleistungen Internat der Müllerschule Wittingen",
      "client": "Landkreis Gifhorn",
      "location": "29378 Wittingen",
      "state": "Bundesweit",
      "deadline": "2026-06-16T08:59:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 29378 Wittingen Vergabestelle: Landkreis Gifhorn Angebotsfrist: 16.06.2026 08:59 Veroeffentlichungsende: 24.07.2026 00:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/subreport/2026/06/E98332684.html"
    },
    {
      "id": "2026-i0-schanlbau-luftfoerdertechnik-staatliches-bauamt-passau-16-06-2026-09-00",
      "title": "2026 I0 SchAnlBau Luftfoerdertechnik",
      "client": "Staatliches Bauamt Passau",
      "location": "94469 Deggendorf",
      "state": "Bundesweit",
      "deadline": "2026-06-16T09:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 94469 Deggendorf Vergabestelle: Staatliches Bauamt Passau Angebotsfrist: 16.06.2026 09:00 Veroeffentlichungsende: 16.06.2026 08:59",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/obb/2026/06/194785.html"
    },
    {
      "id": "neubau-feuerwehrgeratehaus-weene-los-19-reinigungsarbeiten-gemeinde-ihlow-16-06-",
      "title": "Neubau Feuerwehrgerätehaus Weene - Los 19 Reinigungsarbeiten",
      "client": "Gemeinde Ihlow",
      "location": "26632 Ihlow",
      "state": "Bundesweit",
      "deadline": "2026-06-16T09:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 26632 Ihlow Vergabestelle: Gemeinde Ihlow Angebotsfrist: 16.06.2026 09:00 Veroeffentlichungsende: 16.06.2026 09:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/vmp-nds/2026/06/131029.html"
    },
    {
      "id": "gde-visbek-erweiterung-grundschule-rechterfeld-blitzschutzarbeiten-landkreis-vec",
      "title": "Gde. Visbek: Erweiterung Grundschule Rechterfeld - Blitzschutzarbeiten",
      "client": "Landkreis Vechta",
      "location": "Gemeinde Visbek - Rechterfeld Am Sportplatz 3 Visbek",
      "state": "Bundesweit",
      "deadline": "2026-06-16T11:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: Gemeinde Visbek - Rechterfeld Am Sportplatz 3 Visbek Vergabestelle: Landkreis Vechta Angebotsfrist: 16.06.2026 11:00 Veroeffentlichungsende: 16.06.2026 23:59",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/ai-dabl/2026/06/54321-Tender-19e8285b5ef-c0d677d708c8f8c.html"
    },
    {
      "id": "gde-visbek-erweiterung-grundschule-rechterfeld-elektroarbeiten-landkreis-vechta-",
      "title": "Gde. Visbek: Erweiterung Grundschule Rechterfeld - Elektroarbeiten",
      "client": "Landkreis Vechta",
      "location": "Grundschule Rechterfeld, Am Sportplatz 3, Visbek",
      "state": "Bundesweit",
      "deadline": "2026-06-16T12:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: Grundschule Rechterfeld, Am Sportplatz 3, Visbek Vergabestelle: Landkreis Vechta Angebotsfrist: 16.06.2026 12:00 Veroeffentlichungsende: 16.06.2026 23:59",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/ai-dabl/2026/06/54321-Tender-19e8340b149-5578cbacda100519.html"
    },
    {
      "id": "strasseninstandsetzung-hohendubrau-gemeinde-hohendubrau-16-06-2026-14-00",
      "title": "Straßeninstandsetzung Hohendubrau",
      "client": "Gemeinde Hohendubrau",
      "location": "02906 Hohendubrau",
      "state": "Bundesweit",
      "deadline": "2026-06-16T14:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Tiefbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 02906 Hohendubrau Vergabestelle: Gemeinde Hohendubrau Angebotsfrist: 16.06.2026 14:00 Veroeffentlichungsende: 16.06.2026 14:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/evergabede/2026/06/6949017.html"
    },
    {
      "id": "ausbau-1-querweg-in-riepe-tiefbauarbeiten-gemeinde-ihlow-17-06-2026-09-00",
      "title": "Ausbau 1. Querweg in Riepe - Tiefbauarbeiten",
      "client": "Gemeinde Ihlow",
      "location": "26632 Ihlow",
      "state": "Bundesweit",
      "deadline": "2026-06-17T09:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Tiefbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 26632 Ihlow Vergabestelle: Gemeinde Ihlow Angebotsfrist: 17.06.2026 09:00 Veroeffentlichungsende: 17.06.2026 09:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/vmp-nds/2026/06/131114.html"
    },
    {
      "id": "dlr-standort-lampoldshausen-i65-neubau-technische-physik-malerarbeiten-26-0176-b",
      "title": "DLR Standort Lampoldshausen I65 Neubau Technische Physik - Malerarbeiten (26-0176_B)",
      "client": "Deutsches Zentrum für Luft-und Raumfahrt e. V. | TI-ZVM",
      "location": "74239 Hardthausen am Kocher",
      "state": "Bundesweit",
      "deadline": "2026-06-17T09:30:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 74239 Hardthausen am Kocher Vergabestelle: Deutsches Zentrum für Luft-und Raumfahrt e. V. | TI-ZVM Angebotsfrist: 17.06.2026 09:30 Veroeffentlichungsende: 28.08.2026 00:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/subreport/2026/06/E78439726.html"
    },
    {
      "id": "gde-visbek-erweiterung-grundschule-rechterfeld-heizungs-luftungs-und-sanitararbe",
      "title": "Gde. Visbek: Erweiterung Grundschule Rechterfeld - Heizungs-, Lüftungs- und Sanitärarbeiten",
      "client": "Landkreis Vechta",
      "location": "Gemeinde Visbek - OT Rechterfeld Am Sportplatz 3 Visbek",
      "state": "Bundesweit",
      "deadline": "2026-06-17T10:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: Gemeinde Visbek - OT Rechterfeld Am Sportplatz 3 Visbek Vergabestelle: Landkreis Vechta Angebotsfrist: 17.06.2026 10:00 Veroeffentlichungsende: 17.06.2026 23:59",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/ai-dabl/2026/06/54321-Tender-19e8be1e42d-476b8c3c0daced36.html"
    },
    {
      "id": "reinigung-strassenablaufe-2026-hansestadt-stade-17-06-2026-11-00",
      "title": "Reinigung Straßenabläufe 2026",
      "client": "Hansestadt Stade",
      "location": "Gebiet der Hansestadt Stade",
      "state": "Bundesweit",
      "deadline": "2026-06-17T11:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Tiefbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: Gebiet der Hansestadt Stade Vergabestelle: Hansestadt Stade Angebotsfrist: 17.06.2026 11:00 Veroeffentlichungsende: 17.06.2026 23:59",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/ai-dabl/2026/06/54321-Tender-19e6d41e8a1-46c3a69c03e237ac.html"
    },
    {
      "id": "unterhaltsreinigung-kanal-2026-stadt-delbruck-17-06-2026-11-30",
      "title": "Unterhaltsreinigung Kanal 2026",
      "client": "Stadt Delbrück",
      "location": "33129 Delbrück",
      "state": "Bundesweit",
      "deadline": "2026-06-17T11:30:00+02:00",
      "execution": "Noch pruefen",
      "category": "Tiefbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 33129 Delbrück Vergabestelle: Stadt Delbrück Angebotsfrist: 17.06.2026 11:30 Veroeffentlichungsende: 17.06.2026 11:30",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/vmp-westfalen/2026/06/55420076.html"
    },
    {
      "id": "errichtung-garagenkomplex-mit-16-pkw-stellflachen-los-3-hoch-und-tiefbauarbeiten",
      "title": "Errichtung Garagenkomplex mit 16 Pkw-Stellflächen Los 3 Hoch- und Tiefbauarbeiten",
      "client": "Stadtverwaltung Mittweida",
      "location": "09648 Mittweida",
      "state": "Bundesweit",
      "deadline": "2026-06-17T14:04:00+02:00",
      "execution": "Noch pruefen",
      "category": "Tiefbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 09648 Mittweida Vergabestelle: Stadtverwaltung Mittweida Angebotsfrist: Veroeffentlichungsende: 17.06.2026 14:04",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/evergabede/2026/06/6948848.html"
    },
    {
      "id": "sanierung-dach-und-fassade-der-regionalen-schule-zehna-bauleistung-amt-gustrow-l",
      "title": "Sanierung Dach und Fassade der Regionalen Schule Zehna - Bauleistung",
      "client": "Amt Güstrow-Land",
      "location": "18276 Zehna",
      "state": "Bundesweit",
      "deadline": "2026-06-18T09:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 18276 Zehna Vergabestelle: Amt Güstrow-Land Angebotsfrist: 18.06.2026 09:00 Veroeffentlichungsende: 17.07.2026 00:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/subreport/2026/06/E54888498.html"
    },
    {
      "id": "neubau-trauerhalle-schkeuditz-los05-trockenbau-stadtverwaltung-schkeuditz-18-06-",
      "title": "Neubau Trauerhalle Schkeuditz - Los05 Trockenbau",
      "client": "Stadtverwaltung Schkeuditz",
      "location": "04435 Schkeuditz",
      "state": "Bundesweit",
      "deadline": "2026-06-18T09:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 04435 Schkeuditz Vergabestelle: Stadtverwaltung Schkeuditz Angebotsfrist: 18.06.2026 09:00 Veroeffentlichungsende: 18.06.2026 09:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/evergabede/2026/06/6948885.html"
    },
    {
      "id": "samtgemeinde-luchow-wendland-neubau-eines-feuerwehrgeratehauses-in-dunsche-los-2",
      "title": "Samtgemeinde Lüchow (Wendland) - Neubau eines Feuerwehrgerätehauses in Dünsche - Los 27 Photovoltaikanlage",
      "client": "Samtgemeinde Lüchow (Wendland)",
      "location": "29494 Trebel OT Dünsche",
      "state": "Bundesweit",
      "deadline": "2026-06-18T09:30:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 29494 Trebel OT Dünsche Vergabestelle: Samtgemeinde Lüchow (Wendland) Angebotsfrist: 18.06.2026 09:30 Veroeffentlichungsende: 18.06.2026 09:30",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/vmp-nds/2026/06/131132.html"
    },
    {
      "id": "aufzugseinbau-mit-grundrissanderung-los-10-metallbauarbeiten-aluminium-und-schlo",
      "title": "Aufzugseinbau mit Grundrissänderung - Los 10 Metallbauarbeiten Aluminium und Schlosserarbeiten",
      "client": "Bergener Wohnungsgesellschaft mbH",
      "location": "18528 Bergen / Rügen",
      "state": "Bundesweit",
      "deadline": "2026-06-18T10:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 18528 Bergen / Rügen Vergabestelle: Bergener Wohnungsgesellschaft mbH Angebotsfrist: 18.06.2026 10:00 Veroeffentlichungsende: 18.06.2026 10:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/evergabede/2026/06/6950361.html"
    },
    {
      "id": "osterode-herzberg-fahrbahnerneuerung-niedersachsische-landesbehorde-fur-strassen",
      "title": "Osterode - Herzberg Fahrbahnerneuerung",
      "client": "Niedersächsische Landesbehörde für Straßenbau und Verkehr - Geschäftsbereich Goslar",
      "location": "38640 Goslar",
      "state": "Bundesweit",
      "deadline": "2026-06-18T10:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Tiefbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 38640 Goslar Vergabestelle: Niedersächsische Landesbehörde für Straßenbau und Verkehr - Geschäftsbereich Goslar Angebotsfrist: 18.06.2026 10:00 Veroeffentlichungsende: 18.06.2026 10:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/vmp-nds/2026/06/131009.html"
    },
    {
      "id": "gde-visbek-erweiterung-grundschule-rechterfeld-pv-anlage-landkreis-vechta-18-06-",
      "title": "Gde. Visbek: Erweiterung Grundschule Rechterfeld - PV-Anlage",
      "client": "Landkreis Vechta",
      "location": "Gemeinde Visbek Rechterfeld Am Sportplatz 3 49429 Visbek",
      "state": "Bundesweit",
      "deadline": "2026-06-18T10:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: Gemeinde Visbek Rechterfeld Am Sportplatz 3 49429 Visbek Vergabestelle: Landkreis Vechta Angebotsfrist: 18.06.2026 10:00 Veroeffentlichungsende: 18.06.2026 23:59",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/ai-dabl/2026/06/54321-Tender-19e8d1ad577-65f114ac2809dfee.html"
    },
    {
      "id": "beschaffung-von-mobilen-endgeraten-fur-verschiedene-schulen-der-stadt-lennestadt",
      "title": "Beschaffung von mobilen Endgeräten für verschiedene Schulen der Stadt Lennestadt",
      "client": "Stadt Lennestadt",
      "location": "57368 Lennestadt",
      "state": "Bundesweit",
      "deadline": "2026-06-18T10:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 57368 Lennestadt Vergabestelle: Stadt Lennestadt Angebotsfrist: 18.06.2026 10:00 Veroeffentlichungsende: 31.12.2026 00:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/subreport/2026/06/E72578159.html"
    },
    {
      "id": "stadt-cottbus-tnw-124-2026-spreeschule-parasporthalle-prufung-des-geg-nachweises",
      "title": "Stadt Cottbus TNW 124-2026 Spreeschule Parasporthalle Prüfung des GEG Nachweises",
      "client": "Stadtverwaltung Cottbus",
      "location": "03042 Cottbus",
      "state": "Bundesweit",
      "deadline": "2026-06-18T10:30:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 03042 Cottbus Vergabestelle: Stadtverwaltung Cottbus Angebotsfrist: 18.06.2026 10:30 Veroeffentlichungsende: 18.06.2026 10:30",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/vmp-bb/2026/06/254587.html"
    },
    {
      "id": "enderschliessung-baugebiet-heuweg-gemeinde-esterwegen-lk-emsland-uber-samtgemein",
      "title": "Enderschließung Baugebiet Heuweg",
      "client": "Gemeinde Esterwegen (LK Emsland) über Samtgemeinde Nordhümmling",
      "location": "26897 Esterwegen",
      "state": "Bundesweit",
      "deadline": "2026-06-18T11:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 26897 Esterwegen Vergabestelle: Gemeinde Esterwegen (LK Emsland) über Samtgemeinde Nordhümmling Angebotsfrist: 18.06.2026 11:00 Veroeffentlichungsende: 31.12.2026 00:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/subreport/2026/06/E74182571.html"
    },
    {
      "id": "prufung-erstellung-uberarbeitung-und-dokumentation-der-vorhandenen-feuerwehrplan",
      "title": "Prüfung, Erstellung, Überarbeitung und Dokumentation der vorhandenen Feuerwehrpläne HTW Dresden",
      "client": "Hochschule für Technik und Wirtschaft Dresden",
      "location": "01069 Dresden",
      "state": "Bundesweit",
      "deadline": "2026-06-18T13:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 01069 Dresden Vergabestelle: Hochschule für Technik und Wirtschaft Dresden Angebotsfrist: 18.06.2026 13:00 Veroeffentlichungsende: 18.06.2026 13:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/evergabede/2026/06/6950208.html"
    },
    {
      "id": "3-dienstfahrzeuge-hochdachkombi-pkw-elektrisch-landratsamt-ilm-kreis-18-06-2026-",
      "title": "3 Dienstfahrzeuge (Hochdachkombi / PKW - Elektrisch)",
      "client": "Landratsamt Ilm-Kreis",
      "location": "99310 Arnstadt",
      "state": "Bundesweit",
      "deadline": "2026-06-18T13:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 99310 Arnstadt Vergabestelle: Landratsamt Ilm-Kreis Angebotsfrist: 18.06.2026 13:00 Veroeffentlichungsende: 18.06.2026 13:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/evergabede/2026/06/6950189.html"
    },
    {
      "id": "erzgebirgsstadion-aue-gerd-schadlich-platz-1-08280-aue-bad-schlema-erneuerung-mi",
      "title": "Erzgebirgsstadion Aue, Gerd-Schädlich-Platz 1, 08280 Aue-Bad Schlema_ Erneuerung Mittelspannungsanlage _Tiefbauleistungen",
      "client": "Landratsamt Erzgebirgskreis",
      "location": "08280 Aue-Bad Schlema",
      "state": "Bundesweit",
      "deadline": "2026-06-18T13:30:00+02:00",
      "execution": "Noch pruefen",
      "category": "Tiefbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 08280 Aue-Bad Schlema Vergabestelle: Landratsamt Erzgebirgskreis Angebotsfrist: 18.06.2026 13:30 Veroeffentlichungsende: 18.06.2026 13:30",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/evergabede/2026/06/6950112.html"
    },
    {
      "id": "wasserspender-landesamt-fur-bergbau-geologie-und-rohstoffe-veroeffentlichungsend",
      "title": "Wasserspender",
      "client": "Landesamt für Bergbau, Geologie und Rohstoffe",
      "location": "03046 Cottbus",
      "state": "Bundesweit",
      "deadline": "2026-06-18T23:59:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 03046 Cottbus Vergabestelle: Landesamt für Bergbau, Geologie und Rohstoffe Angebotsfrist: Veroeffentlichungsende: 18.06.2026 23:59",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/vmp-bb/2026/06/254522.html"
    },
    {
      "id": "erneuerung-medientechnik-sprachlabor-wwz-technische-hochschule-brandenburg-19-06",
      "title": "Erneuerung Medientechnik Sprachlabor WWZ",
      "client": "Technische Hochschule Brandenburg",
      "location": "14770 Brandenburg an der Havel",
      "state": "Brandenburg",
      "deadline": "2026-06-19T08:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 14770 Brandenburg an der Havel Vergabestelle: Technische Hochschule Brandenburg Angebotsfrist: 19.06.2026 08:00 Veroeffentlichungsende: 19.06.2026 08:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/vmp-bb/2026/06/254532.html"
    },
    {
      "id": "lessing-oberschule-sanierung-fenster-und-fassade-2-ba-los05-trockenbau-anschluss",
      "title": "Lessing-Oberschule - Sanierung Fenster und Fassade 2. BA - Los05 Trockenbau Anschlüsse",
      "client": "Stadtverwaltung Schkeuditz",
      "location": "04435 Schkeuditz",
      "state": "Bundesweit",
      "deadline": "2026-06-19T09:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 04435 Schkeuditz Vergabestelle: Stadtverwaltung Schkeuditz Angebotsfrist: 19.06.2026 09:00 Veroeffentlichungsende: 19.06.2026 09:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/evergabede/2026/06/6950343.html"
    },
    {
      "id": "26b30193-cvo-universitat-oldenburg-botanischer-garten-ausstellungsgebaude-estric",
      "title": "26B30193 - CvO-Universität Oldenburg, Botanischer Garten, Ausstellungsgebäude - Estrich- u. Fliesenarbeiten",
      "client": "Land Niedersachen vertreten durch das Staatliche Baumanagement Niedersachsen",
      "location": "26133 Oldenburg",
      "state": "Bundesweit",
      "deadline": "2026-06-19T09:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 26133 Oldenburg Vergabestelle: Land Niedersachen vertreten durch das Staatliche Baumanagement Niedersachsen Angebotsfrist: Veroeffentlichungsende: 19.06.2026 09:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/vmp-nds/2026/06/131043.html"
    },
    {
      "id": "ersatzneubau-dorfgemeinschaftshaus-leutenthal-los-4-zimmerer-dachdecker-und-dach",
      "title": "Ersatzneubau Dorfgemeinschaftshaus Leutenthal - Los 4: Zimmerer-, Dachdecker- und Dachklempnerarbeiten",
      "client": "Thüringen:Gemeinde Ilmtal-Weinstraße",
      "location": "99510 Ilmtal-Weinstraße OT Leutenthal Leutenthal 17",
      "state": "Bundesweit",
      "deadline": "2026-06-19T10:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Tiefbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 99510 Ilmtal-Weinstraße OT Leutenthal Leutenthal 17 Vergabestelle: Thüringen:Gemeinde Ilmtal-Weinstraße Angebotsfrist: 19.06.2026 10:00 Veroeffentlichungsende: 19.06.2026 10:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/eVergabe/865729.html"
    },
    {
      "id": "sanierung-glasanbauten-los-307-schlosserarbeiten-gelander-hochschule-magdeburg-s",
      "title": "Sanierung Glasanbauten - Los 307 - Schlosserarbeiten Geländer",
      "client": "Hochschule Magdeburg-Stendal",
      "location": "sh. Hauptauftraggeber",
      "state": "Bundesweit",
      "deadline": "2026-06-19T10:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: sh. Hauptauftraggeber Vergabestelle: Hochschule Magdeburg-Stendal Angebotsfrist: 19.06.2026 10:00 Veroeffentlichungsende: 19.06.2026 10:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/eVergabe/865661.html"
    },
    {
      "id": "haus-65-erneuerung-und-erweiterung-der-umluftkuhlgerate-msr-technik-3-ba-univers",
      "title": "Haus 65 - Erneuerung und Erweiterung der Umluftkühlgeräte - MSR-Technik-3.BA",
      "client": "Universitätsklinikum Magdeburg Geschäftsbereich Zentraler Einkauf",
      "location": "Universitätsklinikum Magdeburg A.ö.R. Haus 65 Leipziger Straße 44 39120 Magdeburg",
      "state": "Bundesweit",
      "deadline": "2026-06-19T12:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Tiefbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: Universitätsklinikum Magdeburg A.ö.R. Haus 65 Leipziger Straße 44 39120 Magdeburg Vergabestelle: Universitätsklinikum Magdeburg Geschäftsbereich Zentraler Einkauf Angebotsfrist: 19.06.2026 12:00 Veroeffentlichungsende: 19.06.2026 12:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/eVergabe/865855.html"
    },
    {
      "id": "sgn-ffm-umbau-und-sanierung-aussenstelle-gelnhausen-senckenberg-gesellschaft-fur",
      "title": "SGN Ffm, Umbau und Sanierung Außenstelle Gelnhausen",
      "client": "Senckenberg Gesellschaft für Naturforschung",
      "location": "63571 Gelnhausen",
      "state": "Bundesweit",
      "deadline": "2026-06-19T12:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 63571 Gelnhausen Vergabestelle: Senckenberg Gesellschaft für Naturforschung Angebotsfrist: 19.06.2026 12:00 Veroeffentlichungsende: 20.07.2026 00:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/subreport/2026/06/E41437575.html"
    },
    {
      "id": "hochschule-f-bildende-kunste-neubau-holz-und-keramikwerkstatt-staatsbetrieb-sach",
      "title": "Hochschule f. Bildende Künste, Neubau Holz- und Keramikwerkstatt",
      "client": "Staatsbetrieb Sächsisches Immobilien- und Baumanagement, Zentrale, Zentralstelle Vergabe- und Vertragsmanagement",
      "location": "Hochschule f. Bildende Künste, Neubau Holz- und Keramikwerkstatt Pfotenhauer Str. 81/83, 01307 Dresden",
      "state": "Bundesweit",
      "deadline": "2026-06-22T09:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "mittel",
      "status": "Neu",
      "summary": "Erfuellungsort: Hochschule f. Bildende Künste, Neubau Holz- und Keramikwerkstatt Pfotenhauer Str. 81/83, 01307 Dresden Vergabestelle: Staatsbetrieb Sächsisches Immobilien- und Baumanagement, Zentrale, Zentralstelle Vergabe- und Vertragsmanagement Angebotsfrist: 22.06.2026 09:00 Veroeffentlichungsende: 22.06.2026 23:59",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/sib/2026/06/54321-Tender-19e92891fa7-5e37984db84a3cd1.html"
    },
    {
      "id": "wermsdorf-hubertusburg-aussenanlagen-staatsbetrieb-sachsisches-immobilien-und-ba",
      "title": "Wermsdorf, Hubertusburg, Außenanlagen,",
      "client": "Staatsbetrieb Sächsisches Immobilien- und Baumanagement, Zentrale, Zentralstelle Vergabe- und Vertragsmanagement",
      "location": "Wermsdorf, Hubertusburg, Außenanlagen, , 04779 Wermsdorf",
      "state": "Bundesweit",
      "deadline": "2026-06-22T09:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Tiefbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: Wermsdorf, Hubertusburg, Außenanlagen, , 04779 Wermsdorf Vergabestelle: Staatsbetrieb Sächsisches Immobilien- und Baumanagement, Zentrale, Zentralstelle Vergabe- und Vertragsmanagement Angebotsfrist: 22.06.2026 09:00 Veroeffentlichungsende: 22.06.2026 23:59",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/sib/2026/06/54321-Tender-19e8c8498dd-400f611532e71f3f.html"
    },
    {
      "id": "unterhalts-grund-sonder-bau-und-glasreinigung-integrierte-regionlleitstelle-stad",
      "title": "Unterhalts-, Grund- , Sonder-, Bau- und Glasreinigung Integrierte Regionlleitstelle",
      "client": "Stadt Chemnitz",
      "location": "09112 Chemnitz",
      "state": "Bundesweit",
      "deadline": "2026-06-22T09:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "mittel",
      "status": "Neu",
      "summary": "Erfuellungsort: 09112 Chemnitz Vergabestelle: Stadt Chemnitz Angebotsfrist: 22.06.2026 09:00 Veroeffentlichungsende: 22.06.2026 09:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/evergabede/2026/06/6950182.html"
    },
    {
      "id": "universitat-potsdam-am-neuen-palais-neubau-philosophische-fakultat-1-ba-bodenbel",
      "title": "Universität Potsdam, Am Neuen Palais, Neubau Philosophische Fakultät, 1. BA, Bodenbelagsarbeiten",
      "client": "Brandenburgischer Landesbetrieb für Liegenschaften und Bauen (BLB) - Zentrale Vergabestelle",
      "location": "14469 Potsdam",
      "state": "Bundesweit",
      "deadline": "2026-06-22T10:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "mittel",
      "status": "Neu",
      "summary": "Erfuellungsort: 14469 Potsdam Vergabestelle: Brandenburgischer Landesbetrieb für Liegenschaften und Bauen (BLB) - Zentrale Vergabestelle Angebotsfrist: 22.06.2026 10:00 Veroeffentlichungsende: 22.06.2026 10:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/vmp-bb/2026/06/254604.html"
    },
    {
      "id": "gemeinschaftsschule-teutschenthal-freianlagen-erneuerung-basketballplatz-landkre",
      "title": "Gemeinschaftsschule Teutschenthal_Freianlagen Erneuerung Basketballplatz",
      "client": "Landkreis Saalekreis - Vergabestelle",
      "location": "06179 Gemeinschaftsschule \"Würdetal\" Am Stadion 9, 06179 Teutschenthal",
      "state": "Bundesweit",
      "deadline": "2026-06-22T10:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "mittel",
      "status": "Neu",
      "summary": "Erfuellungsort: 06179 Gemeinschaftsschule \"Würdetal\" Am Stadion 9, 06179 Teutschenthal Vergabestelle: Landkreis Saalekreis - Vergabestelle Angebotsfrist: 22.06.2026 10:00 Veroeffentlichungsende: 22.06.2026 10:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/eVergabe/865716.html"
    },
    {
      "id": "teilerneuerung-spulbohrung-transportleitung-morschbach-rheinhunsruck-wasserzweck",
      "title": "Teilerneuerung Spülbohrung Transportleitung Mörschbach",
      "client": "RheinHunsrück WasserZweckverband",
      "location": "55494 Mörschbach",
      "state": "Bundesweit",
      "deadline": "2026-06-22T10:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Tiefbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 55494 Mörschbach Vergabestelle: RheinHunsrück WasserZweckverband Angebotsfrist: 22.06.2026 10:00 Veroeffentlichungsende: 21.09.2026 00:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/subreport/2026/06/E55829548.html"
    },
    {
      "id": "66-0633-26-tiefbauarbeiten-fur-3-radsammelschliessanlagen-strassenbau-landeshaup",
      "title": "66-0633-26 Tiefbauarbeiten für 3 Radsammelschließanlagen - Straßenbau",
      "client": "Landeshauptstadt Hannover Fachbereich Tiefbau",
      "location": "Hannover",
      "state": "Bundesweit",
      "deadline": "2026-06-22T11:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Tiefbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: Hannover Vergabestelle: Landeshauptstadt Hannover Fachbereich Tiefbau Angebotsfrist: 22.06.2026 11:00 Veroeffentlichungsende: 22.06.2026 11:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/editor/Landeshauptstadt-Hannover/2026/06/6528199.html"
    },
    {
      "id": "haus-65-erneuerung-und-erweiterung-der-umluftkuhlgerate-heizung-luftung-3-ba-uni",
      "title": "Haus 65 - Erneuerung und Erweiterung der Umluftkühlgeräte - Heizung - Lüftung - 3.BA",
      "client": "Universitätsklinikum Magdeburg Geschäftsbereich Zentraler Einkauf",
      "location": "Universitätsklinikum Magdeburg A.ö.R. Haus 65 Leipziger Straße 44 39120 Magdeburg",
      "state": "Bundesweit",
      "deadline": "2026-06-22T12:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Tiefbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: Universitätsklinikum Magdeburg A.ö.R. Haus 65 Leipziger Straße 44 39120 Magdeburg Vergabestelle: Universitätsklinikum Magdeburg Geschäftsbereich Zentraler Einkauf Angebotsfrist: 22.06.2026 12:00 Veroeffentlichungsende: 22.06.2026 12:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/eVergabe/865984.html"
    },
    {
      "id": "schulzentrum-dosner-weg-39-neubau-los-3961-baureinigung-aussen-stadt-leipzig-22-",
      "title": "Schulzentrum Dösner Weg 39, Neubau, Los 3961 Baureinigung-Aussen",
      "client": "Stadt Leipzig",
      "location": "04103 Leipzig",
      "state": "Bundesweit",
      "deadline": "2026-06-22T13:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "mittel",
      "status": "Neu",
      "summary": "Erfuellungsort: 04103 Leipzig Vergabestelle: Stadt Leipzig Angebotsfrist: 22.06.2026 13:00 Veroeffentlichungsende: 22.06.2026 13:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/evergabede/2026/06/6950043.html"
    },
    {
      "id": "erweiterungsbau-altenpflegeheim-in-02763-zittau-los-44-elektroinstallation-zitta",
      "title": "Erweiterungsbau Altenpflegeheim in 02763 Zittau, Los 44 Elektroinstallation",
      "client": "Zittauer Alten- und Pflegeheim GmbH \"St. JAKOB\"",
      "location": "02763 Zittau",
      "state": "Bundesweit",
      "deadline": "2026-06-23T09:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "mittel",
      "status": "Neu",
      "summary": "Erfuellungsort: 02763 Zittau Vergabestelle: Zittauer Alten- und Pflegeheim GmbH \"St. JAKOB\" Angebotsfrist: 23.06.2026 09:00 Veroeffentlichungsende: 23.06.2026 09:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/evergabede/2026/06/6948996.html"
    },
    {
      "id": "bau-einer-loschwasserzisterne-in-der-ortslage-lindenberg-gemeinde-gross-pankow-p",
      "title": "Bau einer Löschwasserzisterne in der Ortslage Lindenberg",
      "client": "Gemeinde Groß Pankow ( Prignitz)",
      "location": "16928 Groß Pankow ( Prignitz)",
      "state": "Bundesweit",
      "deadline": "2026-06-23T10:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "mittel",
      "status": "Neu",
      "summary": "Erfuellungsort: 16928 Groß Pankow ( Prignitz) Vergabestelle: Gemeinde Groß Pankow ( Prignitz) Angebotsfrist: 23.06.2026 10:00 Veroeffentlichungsende: 23.06.2026 10:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/vmp-bb/2026/06/254557.html"
    },
    {
      "id": "ufermauerruckbau-und-wiederherstellung-naturnaher-boschungen-langes-wasser-in-go",
      "title": "Ufermauerrückbau und Wiederherstellung naturnaher Böschungen, Langes Wasser in Göda, 2.BA",
      "client": "Landestalsperrenverwaltung des Freistaates Sachsen, Betrieb Spree/ Neiße",
      "location": "02633 Göda",
      "state": "Bundesweit",
      "deadline": "2026-06-23T10:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "mittel",
      "status": "Neu",
      "summary": "Erfuellungsort: 02633 Göda Vergabestelle: Landestalsperrenverwaltung des Freistaates Sachsen, Betrieb Spree/ Neiße Angebotsfrist: 23.06.2026 10:00 Veroeffentlichungsende: 23.06.2026 10:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/evergabede/2026/06/6950338.html"
    },
    {
      "id": "l01-l02-raddingsdorfer-kreuzung-umbau-knotenpunkt-strassenbauamt-schwerin-23-06-",
      "title": "L01, L02 Raddingsdorfer Kreuzung, Umbau Knotenpunkt",
      "client": "Strassenbauamt Schwerin",
      "location": "19217 Rieps",
      "state": "Bundesweit",
      "deadline": "2026-06-23T10:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Tiefbau",
      "type": "Oeffentlich",
      "priority": "hoch",
      "status": "Neu",
      "summary": "Erfuellungsort: 19217 Rieps Vergabestelle: Strassenbauamt Schwerin Angebotsfrist: 23.06.2026 10:00 Veroeffentlichungsende: 23.06.2026 09:59",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/asp/2026/06/194882.html"
    },
    {
      "id": "dgz-graustein-los-16-estrich-stadt-spremberg-vergabestelle-23-06-2026-10-00",
      "title": "DGZ Graustein - Los 16 - Estrich",
      "client": "Stadt Spremberg - Vergabestelle",
      "location": "03130 Spremberg",
      "state": "Bundesweit",
      "deadline": "2026-06-23T10:00:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "mittel",
      "status": "Neu",
      "summary": "Erfuellungsort: 03130 Spremberg Vergabestelle: Stadt Spremberg - Vergabestelle Angebotsfrist: 23.06.2026 10:00 Veroeffentlichungsende: 23.06.2026 10:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/vmp-bb/2026/06/254519.html"
    },
    {
      "id": "gala-bauarbeiten-und-installation-von-spiel-und-sportgeraten-auf-dem-schulgeland",
      "title": "GALA-Bauarbeiten und Installation von Spiel- und Sportgeräten auf dem Schulgelände, Gymnasium in Hankensbüttel",
      "client": "Landkreis Gifhorn",
      "location": "29386 Hankensbüttel",
      "state": "Bundesweit",
      "deadline": "2026-06-23T10:29:00+02:00",
      "execution": "Noch pruefen",
      "category": "Hochbau",
      "type": "Oeffentlich",
      "priority": "mittel",
      "status": "Neu",
      "summary": "Erfuellungsort: 29386 Hankensbüttel Vergabestelle: Landkreis Gifhorn Angebotsfrist: 23.06.2026 10:29 Veroeffentlichungsende: 28.08.2026 00:00",
      "url": "https://www.service.bund.de/IMPORTE/Ausschreibungen/subreport/2026/06/E47679256.html"
    },
    {
      "id": "private-gewerbliche-bauvorhaben",
      "title": "Private/gewerbliche Bauvorhaben laufend pruefen",
      "client": "ibau, greenprofi, DTAD, regionale Projektmeldungen",
      "location": "Deutschland",
      "state": "Bundesweit",
      "deadline": null,
      "execution": "Laufende Recherche",
      "category": "Privat",
      "type": "Privat/Gewerblich",
      "priority": "mittel",
      "status": "Quelle",
      "summary": "Private Projekte sind oft hinter Portalen oder in fruehen Projektmeldungen. Regelmaessig nach Bauherr, Planer, Gewerk und Region filtern.",
      "url": "https://www.ibau.de/"
    }
  ]
};
